version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - automation
    commit-message:
      prefix: deps
      include: scope

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - automation
      - ci
    commit-message:
      prefix: ci
      include: scope

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - automation
    commit-message:
      prefix: deps
      include: scope

  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - automation
    commit-message:
      prefix: deps
      include: scope
